---
- name: Installing Dependencies
  become: yes
  import_tasks: pre_tasks.yml
- name: Installing apt Packages
  become: yes
  apt:
    pkg: "{{ apt_packages }}"
    state: present
    update_cache: true
- name: Installing snap Packages
  become: yes
  snap:
    name: "{{ snap_packages }}"
    state: present
    classic: yes
